---
- name: Install pgbouncer
  apt:
    name: 'pgbouncer'
    update_cache: yes
    cache_valid_time: '{{ 60 * 60 * 24 }}'
    state: 'present'

- name: Create pgbouncer.ini
  template:
    src: 'pgbouncer.ini.j2'
    dest: '{{ pgbouncer_ini_file }}'
  notify:
    - restart pgbouncer

- name: Create userlist.txt
  template:
    src: 'userlist.txt.j2'
    dest: '{{ pgbouncer_auth_file }}'
  notify:
    - restart pgbouncer

- name: Ensure pgbouncer is started & enabled
  service:
    name: 'pgbouncer'
    state: 'started'
    enabled: yes
